Make sure we have a binary_list.  Bad things happen if we do not

diff --git a/buildroot-generator b/buildroot-generator
--- a/buildroot-generator
+++ b/buildroot-generator
@@ -109,6 +109,14 @@ do
     fi
     let LAYER=${LAYER}+1
     BINARY_LIST=($(dnf ${DNF_OPTIONS} repoquery --srpm --qf %{name} --requires --resolve ${!SOURCE_LIST[@]} 2>/dev/null))
+    if [ ${#BINARY_LIST[@]} -le 0 ] ; then
+      BINARY_LIST=($(dnf ${DNF_OPTIONS} repoquery --srpm --qf %{name} --requires --resolve ${!SOURCE_LIST[@]} 2>/dev/null))
+      if [ ${#BINARY_LIST[@]} -le 0 ] ; then
+        echo "ERROR IN DNF - BINARY PACKAGE LIST IS NOW EMPTY"
+        echo
+        exit 5
+      fi
+    fi
     get_source_name "${BINARY_LIST[@]}"
     get_source_name "$(dnf ${DNF_OPTIONS} repoquery --qf %{name} --requires --resolve --recursive ${BINARY_LIST[@]} 2>/dev/null )"
   
