Optimize archful-srpm-optimization and revise to properly handle changes in package list and/or package versions

diff --git a/identify-archful-srpms b/identify-archful-srpms
--- a/identify-archful-srpms
+++ b/identify-archful-srpms
@@ -3,7 +3,7 @@
 WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 source $WORK_DIR/conf/config.inc
 
-errexit(){
+errexit() {
     echo "$@" >&2
     exit 5
 }
@@ -28,111 +28,216 @@ dnf --quiet clean all
 
 echo "Identifying source packages that may differ based on architecture  ..."
 
-#####
-# Loop through all architectures, merging the buildroot source package lists
-#####
-MERGED_SOURCE_LIST=()
-for this_arch in ${ARCH_LIST[@]}
-do
-  echo "Merging source package list for arch ${this_arch}..."
+# merge_source_package_lists
+#
+# Loop through all architectures, merging the arch-specific buildroot source
+# package lists
+#
+# The merged list of per-arch source package lists is saved as the keys of
+# the global associate array MERGED_SOURCE_LIST, with the value for each key
+# being meaningless.
+merge_source_package_lists() {
+  local this_arch this_package
+  local data_dir timestamp_file src_pkgs_file
+  local timestamp
+  local -a src_pkgs_list
 
-  DATA_DIR="${DATA_DIR_BASE}/${this_arch}/${NEW_DIR}"
-  BR_TIMESTAMP_FILE="${DATA_DIR}/${BR_TIMESTAMP_FILENAME}"
-  BR_SRC_PKGS_FILE="${DATA_DIR}/${BR_SOURCE_PKGNAMES_FILENAME}"
-  if [ ! -r "${BR_TIMESTAMP_FILE}" ] ; then
-    errexit "Missing buildroot timestmap file for arch ${this_arch}: ${BR_TIMESTAMP_FILE}"
-  fi
-  if [ ! -r "${BR_SRC_PKGS_FILE}" ] ; then
-    errexit "Missing buildroot source package list file for arch ${this_arch}: ${BR_SRC_PKGS_FILE}"
-  fi
-
-  TIMESTAMP=$(cat "${BR_TIMESTAMP_FILE}")
-  mapfile -t BR_SRC_PKGS < "${BR_SRC_PKGS_FILE}"
-
-  if [ ${#BR_SRC_PKGS[@]} -eq 0 ] ; then
-    errexit "No buildroot source packages listed in ${BR_SRC_PKGS_FILE}."
-  fi
-
-  #####
-  # Work
-  #####
-
-  echo "Timestap is ${TIMESTAMP}."
-  echo "${#BR_SRC_PKGS[@]} buildroot source packages for arch ${this_arch}."
-
-  for this_package in ${BR_SRC_PKGS[@]}
+  MERGED_SOURCE_LIST=()
+  for this_arch in ${ARCH_LIST[@]}
   do
-    MERGED_SOURCE_LIST[${this_package}]=1
+    echo "Merging source package list for arch ${this_arch}..."
+
+    data_dir="${DATA_DIR_BASE}/${this_arch}/${NEW_DIR}"
+    timestamp_file="${data_dir}/${BR_TIMESTAMP_FILENAME}"
+    src_pkgs_file="${data_dir}/${BR_SOURCE_PKGNAMES_FILENAME}"
+    if [ ! -r "${timestamp_file}" ] ; then
+      errexit "Missing buildroot timestmap file for arch ${this_arch}: ${timestamp_file}"
+    fi
+    if [ ! -r "${src_pkgs_file}" ] ; then
+      errexit "Missing buildroot source package list file for arch ${this_arch}: ${src_pkgs_file}"
+    fi
+
+    timestamp=$(cat "${timestamp_file}")
+    mapfile -t src_pkgs_list < "${src_pkgs_file}"
+
+    if [ ${#src_pkgs_list[@]} -eq 0 ] ; then
+      errexit "No buildroot source packages listed in ${src_pkgs_file}."
+    fi
+
+    echo "Timestap is ${timestamp}."
+    echo "${#src_pkgs_list[@]} buildroot source packages for arch ${this_arch}."
+
+    for this_package in ${src_pkgs_list[@]}
+    do
+      MERGED_SOURCE_LIST[${this_package}]=1
+    done
+
+  # finish with this arch
   done
 
-# finish with this arch
-done
+  echo "${#MERGED_SOURCE_LIST[@]} buildroot source packages for all architectures combined."
+}
 
-echo "${#MERGED_SOURCE_LIST[@]} buildroot source packages for all architectures combined."
 
+# download_source_rpms srpm_dir pkg1 pkg2 ...
+# srpm_dir: directory into which source rpms should be downloaded
+# pkg1 ...: list of base package names for which to download source rpms
+download_source_rpms() {
+  local srpm_dir="$1"
+  shift
+  # pick first arch as forced arch for source download, since they're all the same
+  local src_dl_arch=${ARCH_LIST[0]}
+
+  echo "Downloading SRPMs."
+  dnf --quiet --forcearch=${src_dl_arch} ${DNF_OPTIONS_SOURCE_ONLY} download --downloaddir "${srpm_dir}" --source "$@"
+}
+
+# order_srpm_files srpm1 srpm2
+# srpm1: a source rpm file path
+# srpm2: another source rpm file path
 #
-# TODO? cleanup or archive any existing SRPMs in directory
+# return older file first based on NVR, newer second
+order_srpm_files() {
+  local srpm1="$1" srpm2="$2"
+  local evr1 evr2
+
+  evr1=$(rpm -q --nosignature --qf "%{evr}" -p ${srpm1})
+  evr2=$(rpm -q --nosignature --qf "%{evr}" -p ${srpm2})
+
+  rpmdev-vercmp "$evr1" "$evr2" >/dev/null
+  cmpstat="$?"
+  case "$cmpstat" in
+  0)  # EVRs are equal
+    echo "$srpm1" "$srpm2"
+    ;;
+  11) # EVR1 is newer
+    echo "$srpm2" "$srpm1"
+    ;;
+  12) # EVR2 is newer
+    echo "$srpm1" "$srpm2"
+    ;;
+  *)  # problems
+    echo "Unable to compare $srpm1 and $srpm2!" >&2
+    ;;
+  esac
+}
+
+# check_source_rpms srpm_dir
+# srpm_dir: directory into which source rpms should be downloaded
 #
+# Check that all expected source packages have been downloaded, and remove
+# any extraneous or obsolete source packages.
+#
+# While checking the source rpms, the global associate array
+# SRPM_DOWNLOADED_LIST is constructed. The keys are the base package names
+# for each source rpm file, with the corresponing value for each being the
+# source rpm file path.
+check_source_rpms() {
+  local srpm_dir="$1"
+  local srpm
+  local pkgname
+  local -a ordered_srpms
 
-DATA_DIR="${DATA_DIR_BASE}/source/${NEW_DIR}"
-SRPMS_DIR="${DATA_DIR}/srpms"
-mkdir -p "${SRPMS_DIR}"
+  echo "Checking SRPMs."
 
-echo "Downloading SRPMs."
+  # Create mapping of package names to SRPM files
+  SRPM_DOWNLOADED_LIST=()
+  for srpm in ${srpm_dir}/*.src.rpm
+  do
+    pkgname=$(rpm -q --nosignature --qf "%{name}" -p ${srpm})
 
-# pick first arch for source download, since they're all the same
-src_dl_arch=${ARCH_LIST[0]}
-dnf --quiet --forcearch=${src_dl_arch} ${DNF_OPTIONS_SOURCE_ONLY} download --downloaddir "${SRPMS_DIR}" --source ${!MERGED_SOURCE_LIST[@]}
+    if [ ! -v MERGED_SOURCE_LIST[${pkgname}] ]; then
+      echo "NOTICE: Found extraneous SRPM for package ${pkgname}! Removing."
+      rm -f "${srpm}"
+      continue
+    fi
 
-echo "Checking SRPMs."
+    if [ ! -v SRPM_DOWNLOADED_LIST[${pkgname}] ]; then
+      SRPM_DOWNLOADED_LIST[${pkgname}]="${srpm}"
+    else
+      echo "NOTICE: Found multiple SRPMs for package ${pkgname}. Removing older."
+      # set ordered_srpms[0] to older SRPM, ordered_srpms[1] to newer
+      ordered_srpms=($(order_srpm_files "${srpm}" "${SRPM_DOWNLOADED_LIST[${pkgname}]}"))
+      if [ ${#ordered_srpms[@]} -ne 2 ]; then
+        echo "WARNING: Unable to determine older SRPM for package ${pkgname}!"
+        continue
+      fi
+      # keep newer SRPM
+      SRPM_DOWNLOADED_LIST[${pkgname}]="${ordered_srpms[1]}"
+      # remove old SRPM and any previously extracted spec file
+      rm -f "${ordered_srpms[0]}" "${srpm_dir}/${pkgname}.spec"
+    fi
+  done
 
-# Create mapping of package names to SRPM files
-SRPM_DOWNLOADED_LIST=()
-for srpm in ${SRPMS_DIR}/*.src.rpm
-do
-  pkgname=$(rpm -q --qf "%{name}" -p ${srpm})
-  if [ -v SRPM_DOWNLOADED_LIST[${pkgname}] ]; then
-    echo "WARNING: Found multiple SRPMs for package ${pkgname}!"
-  fi
-  SRPM_DOWNLOADED_LIST[${pkgname}]="${srpm}"
-done
+  # Check that all source packages have been downloaded
+  for pkgname in ${!MERGED_SOURCE_LIST[@]}
+  do
+    if [ ! -v SRPM_DOWNLOADED_LIST[${pkgname}] ]; then
+      echo "WARNING: SRPM for package ${pkgname} was not downloaded!"
+    fi
+  done
+}
 
-# Check that all source packages have been downloaded
-for pkgname in ${!MERGED_SOURCE_LIST[@]}
-do
-  if [ ! -v SRPM_DOWNLOADED_LIST[${pkgname}] ]; then
-    echo "WARNING: SRPM for package ${pkgname} was not downloaded!"
-  fi
-done
 
-# Check each downloaded package to see if it is archful
-ARCHFUL_SOURCE_LIST=()
-for pkgname in ${!SRPM_DOWNLOADED_LIST[@]}
-do
-  srpm=${SRPM_DOWNLOADED_LIST[${pkgname}]}
-  specname="${pkgname}.spec"
-  rpm2cpio ${srpm} | cpio --extract --quiet --unconditional --directory "${SRPMS_DIR}" "${specname}"
+# find_archful_source_packages srpm_dir
+# srpm_dir: directory into which source rpms should be downloaded
+#
+# The list of archful source packages is saved as the keys of the global
+# associate array ARCHFUL_SOURCE_LIST, with the value for each key being
+# meaningless.
+find_archful_source_packages() {
+  local srpm_dir="$1"
+  local pkgname
 
-  specpath="${SRPMS_DIR}/${specname}"
-  if [ ! -r "${specpath}" ] ; then
-    errexit "Failed to extract SPEC file from ${srpm}!"
-  fi
+  # Check each downloaded package to see if it is archful
+  ARCHFUL_SOURCE_LIST=()
+  for pkgname in ${!SRPM_DOWNLOADED_LIST[@]}
+  do
+    srpm=${SRPM_DOWNLOADED_LIST[${pkgname}]}
+    specname="${pkgname}.spec"
+    specpath="${srpm_dir}/${specname}"
 
-  if egrep '[[:blank:]]*%ifn?arch[[:blank:]]' "${specpath}" >/dev/null; then
-    [ "${VERBOSE}" == "TRUE" ] && echo "${pkgname} is archful."
-    ARCHFUL_SOURCE_LIST[${pkgname}]=1
-  else
-    [ "${VERBOSE}" == "TRUE" ] && echo "${pkgname} is NOT archful."
-  fi
-done
+    if [ ! -r "${specpath}" ] ; then
+      rpm2cpio ${srpm} | cpio --extract --quiet --unconditional --directory "${srpm_dir}" "${specname}"
+      if [ ! -r "${specpath}" ] ; then
+	errexit "Failed to extract SPEC file from ${srpm}!"
+      fi
+    fi
 
-echo "${#ARCHFUL_SOURCE_LIST[@]} archful buildroot source packages identified."
+    if egrep '[[:blank:]]*%ifn?arch[[:blank:]]' "${specpath}" >/dev/null; then
+      [ "${VERBOSE}" == "TRUE" ] && echo "${pkgname} is archful."
+      ARCHFUL_SOURCE_LIST[${pkgname}]=1
+    else
+      [ "${VERBOSE}" == "TRUE" ] && echo "${pkgname} is NOT archful."
+    fi
+  done
 
+  echo "${#ARCHFUL_SOURCE_LIST[@]} archful buildroot source packages identified."
+}
+
+# write_archful_source_package_list outfile
+# outfile: file to which to write sorted list
+#
 # Write out the list of archful source packages
-printf "%s\n" "${!ARCHFUL_SOURCE_LIST[@]}" | sort -o "${DATA_DIR}/${BR_ARCHFUL_SOURCE_PKGNAMES_FILENAME}"
+write_archful_source_package_list() {
+  local outfile="$1"
+  printf "%s\n" "${!ARCHFUL_SOURCE_LIST[@]}" | sort -o "$outfile"
+}
 
-#
-# TODO? cleanup SRPMs and/or SPEC files
-#
+data_dir="${DATA_DIR_BASE}/source/${NEW_DIR}"
+srpm_dir="${data_dir}/srpms"
+archful_pkglist_file="${data_dir}/${BR_ARCHFUL_SOURCE_PKGNAMES_FILENAME}"
+
+merge_source_package_lists
+
+mkdir -p "${srpm_dir}"
+
+download_source_rpms "${srpm_dir}" ${!MERGED_SOURCE_LIST[@]}
+
+check_source_rpms "${srpm_dir}"
+
+find_archful_source_packages "${srpm_dir}"
+
+write_archful_source_package_list "${archful_pkglist_file}"
 
 exit 0
